version: "3"
services:
  tor:
    build: . # when bulding over and over, the vanity address will be randomized
    restart: always
  knotresolver:
    image: cznic/knot-resolver:latest
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "18453:8453"
  # knotresolver:
  #   image: subfuzion/netcat
  #   command: ["-vvvl","53"]
  #   tty: true